data:
    src: "eng"
    trg: "deu"

    train: "data/deu-eng/train"
    dev: "data/deu-eng/dev"
    test: "data/deu-eng/test1"

    level: "word"
    lowercase: false
    max_sent_length: 100

    src_vocab_max_size: 30000
    trg_vocab_max_size: 30000
    src_vocab_min_freq: 2
    trg_vocab_min_freq: 2

model:
    encoder:
        type: "transformer"
        num_layers: 4
        num_heads: 4
        hidden_size: 256
        ff_size: 1024
        dropout: 0.2
        embeddings:
            embedding_dim: 256
            dropout: 0.1

    decoder:
        type: "transformer"
        num_layers: 4
        num_heads: 4
        hidden_size: 256
        ff_size: 1024
        dropout: 0.2
        embeddings:
            embedding_dim: 256
            dropout: 0.1

    tied_embeddings: false
    tied_softmax: false

training:
    model_dir: "outputs/ende_transformer_baseline_v1"

    overwrite: false
    random_seed: 42
    use_cuda: true

    optimizer: "adam"
    learning_rate: 0.0005
    learning_rate_min: 1.0e-06
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.7

    loss: "crossentropy"
    label_smoothing: 0.0

    batch_size: 2048
    batch_type: "token"
    batch_multiplier: 1

    clip_grad_norm: 1.0

    epochs: 20
    validation_freq: 1000
    logging_freq: 100

    early_stopping_metric: "bleu"
    keep_best_ckpts: 3
    shuffle: true

    print_valid_sents: [0, 1, 2]